import Link from 'next/link';
import { CreditCard, Lock, MessageCircle, PiggyBank, Smartphone, TrendingUp } from 'lucide-react';
const services=[['Smart Checking',CreditCard],['High-yield Savings',PiggyBank],['Mobile Transfers',Smartphone],['Wealth Insights',TrendingUp]];
export default function Home(){return <>
<section className="relative overflow-hidden bg-gradient-to-br from-blue-700 via-blue-500 to-emerald-400 text-white"><div className="absolute inset-0 bg-[radial-gradient(circle_at_20%_10%,white,transparent_25%)] opacity-20"/><div className="mx-auto grid max-w-7xl items-center gap-10 px-4 py-24 lg:grid-cols-2"><div className="animate-fade-up"><p className="mb-4 font-bold uppercase tracking-[.3em] text-emerald-100">Fictional digital banking</p><h1 className="text-5xl font-black md:text-7xl">Banking UI that feels calm, secure, and intelligent.</h1><p className="mt-6 text-xl text-blue-50">Gradient Grant Bank blends modern gradients, responsive workflows, and customer-friendly tools for a polished demo banking experience.</p><div className="mt-8 flex flex-wrap gap-3"><Link href="/signup" className="btn-primary bg-none bg-white text-blue-700">Open demo account</Link><Link href="/dashboard" className="btn-secondary border-white/40 bg-white/10 text-white">View dashboard</Link></div></div><div className="card animate-float bg-white/15 text-white"><p className="text-sm">Available balance</p><p className="mt-3 text-5xl font-black">$59,360.77</p><div className="mt-8 grid gap-4 sm:grid-cols-2"><div className="rounded-2xl bg-white/15 p-4"><p>Security score</p><b>98%</b></div><div className="rounded-2xl bg-white/15 p-4"><p>Monthly saved</p><b>$1,200</b></div></div></div></div></section>
<section id="services" className="mx-auto max-w-7xl px-4 py-20"><h2 className="text-4xl font-black">Services for every financial moment</h2><div className="mt-8 grid gap-6 md:grid-cols-4">{services.map(([n,Icon]:any)=><div className="card transition hover:-translate-y-1" key={n}><Icon className="mb-4 text-emerald-500"/><h3 className="text-xl font-bold">{n}</h3><p className="mt-2 text-slate-600 dark:text-slate-300">Demo workflows with clear states, accessible forms, and responsive layouts.</p></div>)}</div></section>
<section id="security" className="bg-slate-900 py-20 text-white"><div className="mx-auto grid max-w-7xl gap-8 px-4 md:grid-cols-2"><div><Lock size={44} className="text-emerald-300"/><h2 className="mt-4 text-4xl font-black">Security-first interface patterns</h2><p className="mt-4 text-slate-300">Profile controls, card locks, alerts, and two-factor UI demonstrate how trust can be designed without real backend connections.</p></div><div className="grid gap-4"><div className="rounded-3xl bg-white/10 p-6">Biometric sign-in mock states</div><div className="rounded-3xl bg-white/10 p-6">Instant card freeze controls</div><div className="rounded-3xl bg-white/10 p-6">Privacy-focused disclaimer on every page</div></div></div></section>
<section className="mx-auto max-w-7xl px-4 py-20"><h2 className="text-4xl font-black">Trusted by demo customers</h2><div className="mt-8 grid gap-6 md:grid-cols-3">{['The clean dashboard makes complex banking tasks feel simple.','Transfers and bill pay demos are clear and confidence inspiring.','The dark mode looks premium on desktop and mobile.'].map((q,i)=><blockquote className="card" key={q}>“{q}”<p className="mt-4 font-bold">Customer {i+1}</p></blockquote>)}</div></section>
<section id="faq" className="mx-auto max-w-4xl px-4 py-20"><h2 className="text-4xl font-black">FAQ</h2>{['Is this a real bank? No, it is a fictional demonstration.','Do transfers work? No, all money movement screens are UI only.','Is there real authentication? No, login and sign up are interface demonstrations.'].map(f=><details className="card mt-4" key={f}><summary className="cursor-pointer font-bold">{f.split('?')[0]}?</summary><p className="mt-3 text-slate-600 dark:text-slate-300">{f.split('? ')[1]}</p></details>)}</section>
<section className="bg-gradient-to-r from-blue-600 to-emerald-500 py-16 text-center text-white"><MessageCircle className="mx-auto"/><h2 className="mt-4 text-4xl font-black">Need a guided demo?</h2><Link href="/contact" className="btn-primary mt-6 bg-none bg-white text-blue-700">Contact the demo team</Link></section>
</>}
