'use client';
import Link from 'next/link';
import { Area, AreaChart, Bar, BarChart, Cell, Pie, PieChart, ResponsiveContainer, Tooltip, XAxis } from 'recharts';
import { accounts, spend, transactions } from '@/lib/mockData';
import { ArrowUpRight, CreditCard, Landmark, LockKeyhole, PiggyBank, ShieldCheck, WalletCards } from 'lucide-react';
export const money=(n:number)=>new Intl.NumberFormat('en-US',{style:'currency',currency:'USD'}).format(n);
export function AccountCards(){return <div className="grid gap-5 md:grid-cols-2">{accounts.map(a=><div key={a.type} className={`rounded-3xl bg-gradient-to-br ${a.color} p-6 text-white shadow-glow`}><p>{a.type}</p><p className="mt-8 text-4xl font-black">{money(a.balance)}</p><div className="mt-6 flex justify-between"><span>{a.number}</span><span>{a.change}</span></div></div>)}</div>}
export function TransactionTable(){return <div className="card overflow-x-auto"><h2 className="mb-4 text-2xl font-bold">Transaction history</h2><table className="w-full text-left text-sm"><tbody>{transactions.map(t=><tr key={t.merchant} className="border-t border-slate-100 dark:border-white/10"><td className="py-4 font-semibold">{t.merchant}<p className="text-slate-500">{t.category}</p></td><td>{t.date}</td><td className={`text-right font-bold ${t.amount>0?'text-emerald-500':'text-slate-700 dark:text-slate-200'}`}>{money(t.amount)}</td></tr>)}</tbody></table></div>}
export function AnalyticsCharts(){const colors=['#2563eb','#10b981','#06b6d4','#8b5cf6','#14b8a6'];return <div className="grid gap-6 lg:grid-cols-2"><div className="card h-80"><h2 className="font-bold">Monthly spending</h2><ResponsiveContainer width="100%" height="85%"><BarChart data={spend}><XAxis dataKey="name"/><Tooltip/><Bar dataKey="value" radius={[10,10,0,0]}>{spend.map((_,i)=><Cell key={i} fill={colors[i]}/>)}</Bar></BarChart></ResponsiveContainer></div><div className="card h-80"><h2 className="font-bold">Savings momentum</h2><ResponsiveContainer width="100%" height="85%"><AreaChart data={[{m:'Jan',v:38},{m:'Feb',v:40},{m:'Mar',v:43},{m:'Apr',v:44},{m:'May',v:46},{m:'Jun',v:48}]}><XAxis dataKey="m"/><Tooltip/><Area type="monotone" dataKey="v" stroke="#10b981" fill="#10b98155"/></AreaChart></ResponsiveContainer></div></div>}
export function QuickActions(){const items=[['Transfer','/transfer',ArrowUpRight],['Bills','/bills',Landmark],['Loans','/loans',PiggyBank],['Cards','/cards',CreditCard],['Profile','/profile',ShieldCheck],['Admin','/admin',LockKeyhole]];return <div className="grid grid-cols-2 gap-4 md:grid-cols-3 lg:grid-cols-6">{items.map(([n,h,Icon]:any)=><Link href={h} key={n} className="card text-center transition hover:-translate-y-1"><Icon className="mx-auto mb-3 text-blue-600"/><span className="font-semibold">{n}</span></Link>)}</div>}
export function DemoForm({type}:{type:string}){return <form className="card mx-auto max-w-2xl space-y-4"><div className="flex items-center gap-3 text-blue-600"><WalletCards/><h2 className="text-2xl font-bold">{type}</h2></div><input className="input" placeholder="From account"/><input className="input" placeholder="Recipient or payee"/><input className="input" placeholder="Amount"/><textarea className="input" placeholder="Memo"/><button type="button" className="btn-primary w-full">Preview demo action</button><p className="text-sm text-slate-500">Demo only: this interface does not submit, store, or move real funds.</p></form>}
export function PieSpend(){return <div className="card h-96"><ResponsiveContainer><PieChart><Pie data={spend} dataKey="value" nameKey="name" outerRadius={120} label>{spend.map((_,i)=><Cell key={i} fill={['#2563eb','#10b981','#06b6d4','#8b5cf6','#14b8a6'][i]}/>)}</Pie><Tooltip/></PieChart></ResponsiveContainer></div>}
